name: Kaggle Submission

on:
  push:
    branches: [ main ]
    paths:
      - 'configs/**'
      - 'src/**'
      - 'submission/**'
  workflow_dispatch:
    inputs:
      config:
        description: 'Config name to use (default is default.yaml)'
        required: false
        default: 'default'
      competition:
        description: 'Kaggle competition name'
        required: true
      message:
        description: 'Submission message'
        required: true
        default: 'Submission from GitHub Actions'

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download competition data
        run: |
          kaggle competitions download -c ${{ github.event.inputs.competition || 'placeholder-competition' }}
          mkdir -p data/raw
          unzip -o *.zip -d data/raw

      - name: Make prediction and submit
        run: |
          CONFIG=${{ github.event.inputs.config || 'default' }}
          COMPETITION=${{ github.event.inputs.competition }}
          MESSAGE="${{ github.event.inputs.message || 'Submission from GitHub Actions' }}"
          
          python submission/make_submission.py --config $CONFIG --upload --competition "$COMPETITION" --message "$MESSAGE"
          
      - name: Archive submission
        uses: actions/upload-artifact@v3
        with:
          name: submission-files
          path: submission/*.csv 